#ifndef __ERROR_CODES_H__
#define __ERROR_CODES_H__

namespace JaCoAP
{
enum class ErrCode
{
    OK = 0,
    INVALID_ARG,
    OUT_OF_MEMORY,
    MSG_FORMAT_ERROR,
    DGRAM_TOO_SMALL,
    PAYLOAD_TOO_LARGE,
    INVALID_VERSION,
    BAD_MSG,
    OPTION_LEN_RANGE_OUT,
    OPTION_REPEAT_MORE,
    OPTION_CRITICAL_LEN_RANGE_OUT,
    OPTION_CRITICAL_REPEAT_MORE,
    OPTION_CRITICAL_UNKNOWN,
    OPTION_UNKNOWN,
    NULL_POINTER
};
}

#endif /*__ERROR_CODES_H__*/